// src/features/content/CourseContent.vue
<script setup lang="ts">
/**
 * CourseContent — 替代 React 的 features/content/CourseContent.jsx
 * 渲染课程 HTML 正文，并处理数学公式、测验委托、折叠区域和滚动监听。
 */
import { ref, watch, onMounted, onUnmounted } from 'vue'

const props = defineProps<{
  html: string
  courseKey: string
  onQuizAnswer?: (info: { correct: number; chosen: number; container: HTMLElement }) => void
}>()

const containerRef = ref<HTMLDivElement | null>(null)

// ── 数学公式渲染 ──
function renderMath() {
  const el = containerRef.value
  if (!el) return
  const w = window as unknown as Record<string, unknown>
  if (['probability', 'algorithm', 'calculus'].includes(props.courseKey)) {
    if (typeof w['renderMathInElement'] === 'function') {
      try {
        ;(w['renderMathInElement'] as (el: Element, opts: unknown) => void)(el, {
          delimiters: [
            { left: '$$', right: '$$', display: true },
            { left: '\\[', right: '\\]', display: true },
            { left: '\\(', right: '\\)', display: false },
            { left: '$', right: '$', display: false },
          ],
          throwOnError: false,
        })
      } catch (e) {
        console.warn('KaTeX error:', e)
      }
    }
  }
  if (['dsp', 'signals'].includes(props.courseKey)) {
    const mj = w['MathJax'] as { typesetPromise?: (els: Element[]) => Promise<void> } | undefined
    if (mj?.typesetPromise) {
      mj.typesetPromise([el]).catch(() => {})
    }
  }
}

// ── 测验委托 (checkQuiz) ──
function setupQuiz() {
  const w = window as unknown as Record<string, unknown>
  w['checkQuiz'] = function (btn: HTMLElement) {
    if (!btn) return
    const c = btn.closest('.quiz-container') as HTMLElement | null
    const container = c || (btn.parentElement as HTMLElement)
    if (!container || container.dataset['correct'] === undefined) return
    const correct = parseInt(container.dataset['correct'] as string)
    const sel = container.querySelector<HTMLInputElement>('input:checked')
    const res = container.querySelector<HTMLElement>('.quiz-result')
    if (!sel) {
      if (res) {
        res.textContent = '请先选择答案'
        res.className = 'quiz-result quiz-wrong'
        res.style.display = 'block'
      }
      return
    }
    const chosen = parseInt(sel.value)
    if (chosen === correct) {
      if (res) {
        res.textContent = '✓ 正确！'
        res.className = 'quiz-result quiz-correct'
        res.style.display = 'block'
      }
    } else {
      const labels = container.querySelectorAll('.quiz-options label, label')
      if (res) {
        res.textContent = '✗ 错误，正确答案是 ' + (labels[correct]?.textContent?.trim() || '')
        res.className = 'quiz-result quiz-wrong'
        res.style.display = 'block'
      }
    }
    props.onQuizAnswer?.({ correct, chosen, container })
  }
  return () => {
    delete (window as unknown as Record<string, unknown>)['checkQuiz']
  }
}

// ── 折叠区域 ──
function setupCollapsibles() {
  const el = containerRef.value
  if (!el) return
  function handleClick(e: Event) {
    const header = (e.target as HTMLElement).closest(
      '.section-header, h3.collapsible, h4.collapsible, .chapter-header, .card-header',
    ) as HTMLElement | null
    if (!header) return
    e.preventDefault()
    const section = header.closest('.section')
    if (section) {
      section.classList.toggle('collapsed')
      return
    }
    if (header.classList.contains('chapter-header')) {
      header.closest('.chapter')?.classList.toggle('open')
      return
    }
    if (header.classList.contains('card-header')) {
      header.closest('.card')?.classList.toggle('open')
      return
    }
    header.classList.toggle('open')
    const content = header.nextElementSibling
    if (content?.classList.contains('collapsible-content')) content.classList.toggle('show')
  }
  el.addEventListener('click', handleClick)
  return () => el.removeEventListener('click', handleClick)
}

// ── 侧边栏滚动监听 ──
let scrollRAF = 0
function updateNavHighlight() {
  cancelAnimationFrame(scrollRAF)
  scrollRAF = requestAnimationFrame(() => {
    const el = containerRef.value
    if (!el) return
    const ids = el.querySelectorAll('[id]')
    let currentId = ''
    ids.forEach((node) => {
      if (node.getBoundingClientRect().top <= 110) currentId = node.id
    })
    document.querySelectorAll('.sidebar a').forEach((a) => {
      a.classList.toggle('active', a.getAttribute('href') === '#' + currentId)
    })
  })
}

// ── 返回顶部按钮 ──
function handleBackTopScroll() {
  const btn = document.getElementById('backTop') as HTMLElement | null
  if (btn) btn.style.display = window.scrollY > 300 ? 'flex' : 'none'
}

let cleanupQuiz: (() => void) | undefined
let cleanupCollapsibles: (() => void) | undefined

watch(
  () => props.html,
  () => {
    cleanupCollapsibles?.()
    cleanupQuiz?.()
    renderMath()
    cleanupQuiz = setupQuiz()
    // 等 DOM 更新后再绑定折叠
    setTimeout(() => {
      cleanupCollapsibles = setupCollapsibles()
    }, 0)
  },
)

onMounted(() => {
  renderMath()
  cleanupQuiz = setupQuiz()
  cleanupCollapsibles = setupCollapsibles()
  window.addEventListener('scroll', updateNavHighlight, { passive: true })
  window.addEventListener('scroll', handleBackTopScroll, { passive: true })
  updateNavHighlight()
  handleBackTopScroll()
})

onUnmounted(() => {
  cleanupQuiz?.()
  cleanupCollapsibles?.()
  window.removeEventListener('scroll', updateNavHighlight)
  window.removeEventListener('scroll', handleBackTopScroll)
})
</script>

<template>
  <div ref="containerRef" class="course-content" v-html="html" />
</template>

// src/features/content/CourseContent.jsx
import { useEffect, useRef, useCallback } from 'react'
import { useLocation } from 'react-router-dom'

/**
 * Renders course HTML content with post-mount processing:
 * - Math rendering (KaTeX for probability, MathJax for DSP)
 * - Quiz event delegation (checkQuiz)
 * - Collapsible section toggling
 * - Scroll spy for sidebar nav highlighting
 */
export default function CourseContent({ html, courseKey, onQuizAnswer }) {
  const containerRef = useRef(null)
  const location = useLocation()

  // ── Math rendering ──
  useEffect(() => {
    if (!containerRef.current) return
    const el = containerRef.current

    // KaTeX (probability, algorithm, calculus)
    if (courseKey === 'probability' || courseKey === 'algorithm' || courseKey === 'calculus') {
      if (window.renderMathInElement) {
        try {
          window.renderMathInElement(el, {
            delimiters: [
              { left: '$$', right: '$$', display: true },
              { left: '\\[', right: '\\]', display: true },
              { left: '\\(', right: '\\)', display: false },
              { left: '$', right: '$', display: false },
            ],
            throwOnError: false,
          })
        } catch (e) { console.warn('KaTeX error:', e) }
      }
    }

    // MathJax (DSP, Signals)
    if (courseKey === 'dsp' || courseKey === 'signals') {
      if (window.MathJax && window.MathJax.typesetPromise) {
        try {
          window.MathJax.typesetPromise([el]).catch(() => {})
        } catch (e) {}
      }
    }
  }, [html, courseKey])

  // ── Quiz checkQuiz delegation ──
  useEffect(() => {
    // Expose checkQuiz on window for inline onclick handlers in the HTML
    window.checkQuiz = function(btn) {
      if (!btn) return
      const c = btn.closest('.quiz-container')
      if (!c) return
      const correct = parseInt(c.dataset.correct)
      const sel = c.querySelector('input:checked')
      const res = c.querySelector('.quiz-result')
      if (!sel) {
        if (res) { res.textContent = '请先选择答案'; res.className = 'quiz-result quiz-wrong'; res.style.display = 'block' }
        return
      }
      const chosen = parseInt(sel.value)
      if (chosen === correct) {
        if (res) { res.textContent = '✓ 正确！'; res.className = 'quiz-result quiz-correct'; res.style.display = 'block' }
      } else {
        const labels = c.querySelectorAll('.quiz-options label')
        if (res) {
          res.textContent = '✗ 错误，正确答案是 ' + (labels[correct] ? labels[correct].textContent.trim() : '')
          res.className = 'quiz-result quiz-wrong'
          res.style.display = 'block'
        }
      }
      // Notify parent (for wrong-book tracking)
      if (onQuizAnswer) {
        onQuizAnswer({ correct, chosen, container: c })
      }
    }

    // Also handle DSP-style checkQuiz (btn.parentElement instead of btn.closest)
    const origCheckQuiz = window.checkQuiz
    window.checkQuiz = function(btn) {
      origCheckQuiz(btn)
      // DSP uses btn.parentElement as container
      if (btn && !btn.closest('.quiz-container')) {
        const c = btn.parentElement
        if (c && c.dataset.correct !== undefined) {
          const correct = parseInt(c.dataset.correct)
          const sel = c.querySelector('input:checked')
          const res = c.querySelector('.quiz-result')
          if (sel && res) {
            const chosen = parseInt(sel.value)
            if (res.textContent === '') {
              if (chosen === correct) {
                res.textContent = '✓ 正确！'; res.className = 'quiz-result quiz-correct'
              } else {
                const labels = c.querySelectorAll('label')
                res.textContent = '✗ 错误，正确答案是 ' + (labels[correct] ? labels[correct].textContent.trim() : '')
                res.className = 'quiz-result quiz-wrong'
              }
              res.style.display = 'block'
            }
          }
        }
      }
    }

    return () => { delete window.checkQuiz }
  }, [onQuizAnswer])

  // ── Collapsible section toggling ──
  useEffect(() => {
    if (!containerRef.current) return
    const el = containerRef.current

    function handleClick(e) {
      const header = e.target.closest('.section-header, h3.collapsible, h4.collapsible, .chapter-header, .card-header')
      if (!header) return
      e.preventDefault()

      // Toggle collapsed class on parent section
      const section = header.closest('.section')
      if (section) {
        section.classList.toggle('collapsed')
        return
      }

      // Toggle chapter open/close
      if (header.classList.contains('chapter-header')) {
        const chapter = header.closest('.chapter')
        if (chapter) {
          chapter.classList.toggle('open')
          return
        }
      }

      // Toggle card open/close
      if (header.classList.contains('card-header')) {
        const card = header.closest('.card')
        if (card) {
          card.classList.toggle('open')
          return
        }
      }

      // Toggle collapsible content (DSP/algorithm pattern)
      header.classList.toggle('open')
      const content = header.nextElementSibling
      if (content && content.classList.contains('collapsible-content')) {
        content.classList.toggle('show')
      }
    }

    el.addEventListener('click', handleClick)
    return () => el.removeEventListener('click', handleClick)
  }, [html])

  // ── Scroll spy: highlight active nav link ──
  const updateNavHighlight = useCallback(() => {
    if (!containerRef.current) return
    const ids = containerRef.current.querySelectorAll('[id]')
    let currentId = ''
    const offset = 100

    ids.forEach(el => {
      const rect = el.getBoundingClientRect()
      if (rect.top <= offset + 10) currentId = el.id
    })

    document.querySelectorAll('.sidebar a').forEach(a => {
      a.classList.toggle('active', a.getAttribute('href') === '#' + currentId)
    })
  }, [])

  useEffect(() => {
    window.addEventListener('scroll', updateNavHighlight, { passive: true })
    updateNavHighlight()
    return () => window.removeEventListener('scroll', updateNavHighlight)
  }, [updateNavHighlight])

  // ── Back to top visibility ──
  useEffect(() => {
    const btn = document.getElementById('backTop')
    if (!btn) return
    const handler = () => {
      btn.style.display = window.scrollY > 300 ? 'flex' : 'none'
    }
    window.addEventListener('scroll', handler, { passive: true })
    handler()
    return () => window.removeEventListener('scroll', handler)
  }, [])

  return (
    <div
      ref={containerRef}
      className="course-content"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}
