// src/features/exam/ExamQuery.vue
<script setup lang="ts">
/**
 * ExamQuery — 替代 React 的 features/exam/ExamQuery.jsx
 * 根据班级 ID 查询考试安排，带实时倒计时。
 */
import { ref, onMounted, onUnmounted } from 'vue'

const LS_KEY = 'exam_class_id'
const LS_DELETED = 'exam_deleted'

interface ExamEntry {
  course: string
  date: string
  start: string
  end: string
  room: string
  teacher: string
  type: 'school' | 'college'
  iso: string
}

function getDeletedExams(): Record<string, string[]> {
  try {
    return JSON.parse(localStorage.getItem(LS_DELETED) || '{}')
  } catch {
    return {}
  }
}
function isDeleted(classId: string, key: string) {
  const d = getDeletedExams()
  return !!(d[classId] && d[classId].includes(key))
}
function markDeleted(classId: string, key: string) {
  const d = getDeletedExams()
  if (!d[classId]) d[classId] = []
  if (!d[classId].includes(key)) d[classId].push(key)
  try {
    localStorage.setItem(LS_DELETED, JSON.stringify(d))
  } catch {
    /* noop */
  }
}
function getCourseKey(e: ExamEntry) {
  return e.course + '|' + e.date + '|' + e.start
}
function cleanOldDeleted(classId: string) {
  const d = getDeletedExams()
  if (!d[classId]) return
  const now = Date.now()
  d[classId] = d[classId].filter((k) => {
    const p = k.split('|')
    return p.length >= 2 && now - new Date(p[1]).getTime() < 30 * 86400000
  })
  if (!d[classId].length) delete d[classId]
  try {
    localStorage.setItem(LS_DELETED, JSON.stringify(d))
  } catch {
    /* noop */
  }
}
function formatDate(ds: string) {
  const p = ds.split('-'),
    m = parseInt(p[1]),
    d = parseInt(p[2])
  return m + '月' + d + '日 周' + ['日', '一', '二', '三', '四', '五', '六'][new Date(ds).getDay()]
}
function countdown(iso: string) {
  const diff = new Date(iso).getTime() - Date.now()
  if (diff <= 0) return '已开始！'
  const d = Math.floor(diff / 86400000),
    h = Math.floor((diff % 86400000) / 3600000)
  const m = Math.floor((diff % 3600000) / 60000),
    s = Math.floor((diff % 60000) / 1000)
  return d > 0
    ? `${d} 天 ${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
    : `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
}

const classId = ref('')
const queryId = ref('')
const exams = ref<ExamEntry[]>([])
const deletedCount = ref(0)
const showResult = ref(false)
const msg = ref<{ text: string; type: string } | null>(null)
const loading = ref(false)
const countdowns = ref<Record<number, string>>({})

let cachedData: Record<string, ExamEntry[]> | null = null
let refreshTimer: ReturnType<typeof setInterval> | null = null
let cdTimer: ReturnType<typeof setInterval> | null = null

async function loadData() {
  if (cachedData) return cachedData
  const w = window as unknown as Record<string, unknown>
  if (w['EXAM_SCHEDULE_DATA'])
    return (cachedData = w['EXAM_SCHEDULE_DATA'] as Record<string, ExamEntry[]>)
  try {
    const res = await fetch('/files/exam-schedule.json')
    return (cachedData = (await res.json()) as Record<string, ExamEntry[]>)
  } catch {
    return new Promise<Record<string, ExamEntry[]>>((resolve) => {
      const s = document.createElement('script')
      s.src = '/files/exam-schedule-data.js'
      s.onload = () => {
        cachedData = w['EXAM_SCHEDULE_DATA'] as Record<string, ExamEntry[]>
        resolve(cachedData)
      }
      document.head.appendChild(s)
    })
  }
}

async function doQuery(id: string) {
  if (!id.trim()) return
  loading.value = true
  try {
    const d = await loadData()
    if (!d) {
      msg.value = { text: '加载考试数据失败，请稍后再试。', type: 'error' }
      return
    }
    id = id.trim().toUpperCase()
    let targetId = id,
      examsArr = d[id]
    if (!examsArr) {
      const matches = Object.keys(d).filter((k) => k.includes(id))
      if (matches.length === 1) {
        targetId = matches[0]
        examsArr = d[targetId]
      } else if (matches.length > 1) {
        msg.value = {
          text: '多个匹配：' + matches.slice(0, 8).join('、') + '，请输入完整 ID。',
          type: 'warn',
        }
        return
      } else {
        msg.value = { text: '未找到班级「' + id + '」的考试安排。', type: 'warn' }
        return
      }
    }
    queryId.value = targetId
    try {
      localStorage.setItem(LS_KEY, targetId)
    } catch {
      /* noop */
    }
    cleanOldDeleted(targetId)
    const now = new Date()
    let delCnt = 0
    const visible = examsArr.filter((e) => {
      if (new Date(e.iso) < now) return false
      if (isDeleted(targetId, getCourseKey(e))) {
        delCnt++
        return false
      }
      return true
    })
    exams.value = visible
    deletedCount.value = delCnt
    showResult.value = true
    msg.value = null
    // 倒计时
    cdTimer && clearInterval(cdTimer)
    const tick = () => {
      const m: Record<number, string> = {}
      visible.forEach((e, i) => {
        m[i] = countdown(e.iso)
      })
      countdowns.value = m
    }
    tick()
    cdTimer = setInterval(tick, 1000)
  } finally {
    loading.value = false
    if (refreshTimer) clearInterval(refreshTimer)
    refreshTimer = setInterval(() => doQuery(queryId.value), 3600000)
  }
}

function removeExam(idx: number) {
  const e = exams.value[idx]
  markDeleted(queryId.value, getCourseKey(e))
  exams.value.splice(idx, 1)
  if (!exams.value.length) {
    showResult.value = false
    msg.value = { text: '所有考试已结束或已清除，切换班级可重新查询。', type: 'warn' }
  }
}

function clearQuery() {
  try {
    localStorage.removeItem(LS_KEY)
  } catch {
    /* noop */
  }
  if (refreshTimer) clearInterval(refreshTimer)
  queryId.value = ''
  exams.value = []
  showResult.value = false
  msg.value = null
  classId.value = ''
}

function resetDeleted() {
  const d = getDeletedExams()
  delete d[queryId.value]
  try {
    localStorage.setItem(LS_DELETED, JSON.stringify(d))
  } catch {
    /* noop */
  }
  doQuery(queryId.value)
}

onMounted(() => {
  const saved = localStorage.getItem(LS_KEY)
  if (saved) {
    classId.value = saved
    doQuery(saved)
  } else loadData()
})
onUnmounted(() => {
  if (refreshTimer) clearInterval(refreshTimer)
  if (cdTimer) clearInterval(cdTimer)
})
</script>

<template>
  <div class="exam-section">
    <!-- 查询框 -->
    <div v-show="!showResult" id="examInput" class="exam-input-wrap">
      <div class="exam-input-title">📅 查询考试安排</div>
      <div class="exam-input-row">
        <input
          id="examClassInput"
          v-model="classId"
          placeholder="输入班级 ID（如 B220207）"
          autocomplete="off"
          spellcheck="false"
          @keydown.enter="doQuery(classId)"
        />
        <button :disabled="loading" @click="doQuery(classId)">
          {{ loading ? '加载中…' : '查询' }}
        </button>
      </div>
      <div class="exam-input-hint">输入班级 ID 即可查看该班所有考试时间、教室和教师信息</div>
      <div v-if="msg" :class="'exam-msg exam-msg-' + msg.type" style="margin-top: 12px">
        {{ msg.text }}
      </div>
    </div>

    <!-- 结果列表 -->
    <div v-if="showResult" class="exam-result">
      <div class="exam-header">
        <div class="exam-title">
          <span class="exam-class-badge">{{ queryId }}</span> 考试安排
          <span class="exam-count">{{ exams.length }} 门</span>
        </div>
        <div class="exam-header-btns">
          <button v-if="deletedCount > 0" class="exam-reset" @click="resetDeleted">
            恢复 {{ deletedCount }} 门
          </button>
          <button class="exam-switch" @click="clearQuery">切换班级</button>
        </div>
      </div>
      <div v-if="exams.length === 0" class="exam-msg exam-msg-warn">
        所有考试已结束或已清除，切换班级可重新查询。
      </div>
      <div v-else class="exam-scroll-window">
        <div class="exam-list">
          <div v-for="(ev, j) in exams" :key="j" class="exam-card">
            <button class="exam-del" title="移除" @click="removeExam(j)">&times;</button>
            <div class="exam-card-top">
              <div class="exam-course">{{ ev.course }}</div>
              <span :class="'exam-type-tag exam-type-' + ev.type">{{
                ev.type === 'school' ? '校考' : '院考'
              }}</span>
            </div>
            <div class="exam-card-grid">
              <div class="exam-info">
                <span class="exam-label">日期</span
                ><span class="exam-value">{{ formatDate(ev.date) }}</span>
              </div>
              <div class="exam-info">
                <span class="exam-label">时间</span
                ><span class="exam-value">{{ ev.start }} - {{ ev.end }}</span>
              </div>
              <div class="exam-info">
                <span class="exam-label">教室</span><span class="exam-value">{{ ev.room }}</span>
              </div>
              <div class="exam-info">
                <span class="exam-label">教师</span><span class="exam-value">{{ ev.teacher }}</span>
              </div>
            </div>
            <div v-if="ev.iso && new Date(ev.iso) > new Date()" class="exam-countdown">
              距考试还有 <span class="live-countdown">{{ countdowns[j] }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// src/features/exam/ExamQuery.jsx
import { useState, useEffect, useRef, useCallback } from 'react'

const LS_KEY = 'exam_class_id'
const LS_DELETED = 'exam_deleted'

function getDeletedExams() {
  try { return JSON.parse(localStorage.getItem(LS_DELETED) || '{}') } catch (e) { return {} }
}
function isDeleted(classId, key) {
  const d = getDeletedExams()
  return d[classId] && d[classId].indexOf(key) !== -1
}
function markDeleted(classId, key) {
  const d = getDeletedExams()
  if (!d[classId]) d[classId] = []
  if (d[classId].indexOf(key) === -1) d[classId].push(key)
  try { localStorage.setItem(LS_DELETED, JSON.stringify(d)) } catch (e) {}
}
function getCourseKey(exam) { return exam.course + '|' + exam.date + '|' + exam.start }

function cleanOldDeleted(classId) {
  const d = getDeletedExams()
  if (!d[classId]) return
  const now = new Date(), kept = []
  d[classId].forEach(k => {
    const parts = k.split('|')
    if (parts.length >= 2 && now - new Date(parts[1]) < 30 * 86400000) kept.push(k)
  })
  if (kept.length === 0) delete d[classId]; else d[classId] = kept
  try { localStorage.setItem(LS_DELETED, JSON.stringify(d)) } catch (e) {}
}

function formatDate(ds) {
  const p = ds.split('-'), m = parseInt(p[1]), d = parseInt(p[2])
  const wd = ['日','一','二','三','四','五','六'][new Date(ds).getDay()]
  return m + '月' + d + '日 周' + wd
}

function getCountdown(iso) {
  const diff = new Date(iso) - new Date()
  if (diff <= 0) return ''
  const days = Math.floor(diff / 86400000), hours = Math.floor((diff % 86400000) / 3600000)
  if (days > 0) return `${days} 天 ${hours} 小时`
  if (hours > 0) return `${hours} 小时`
  return Math.floor((diff % 3600000) / 60000) + ' 分钟'
}

export default function ExamQuery() {
  const [data, setData] = useState(null)
  const [classId, setClassId] = useState('')
  const [queryId, setQueryId] = useState('')
  const [exams, setExams] = useState([])
  const [deletedCount, setDeletedCount] = useState(0)
  const [showResult, setShowResult] = useState(false)
  const [msg, setMsg] = useState(null)
  const [deletedMap, setDeletedMap] = useState(getDeletedExams)
  const [loading, setLoading] = useState(false)
  const refreshRef = useRef(null)
  const loadedRef = useRef(false)

  const loadData = useCallback(() => {
    return new Promise(resolve => {
      if (loadedRef.current && data) { resolve(data); return }
      if (window.EXAM_SCHEDULE_DATA && typeof window.EXAM_SCHEDULE_DATA === 'object') {
        loadedRef.current = true; setData(window.EXAM_SCHEDULE_DATA); resolve(window.EXAM_SCHEDULE_DATA); return
      }
      fetch('/files/exam-schedule.json')
        .then(r => r.json()).then(j => { loadedRef.current = true; setData(j); resolve(j) })
        .catch(() => {
          const script = document.createElement('script')
          script.src = '/files/exam-schedule-data.js'
          script.onload = () => { loadedRef.current = true; setData(window.EXAM_SCHEDULE_DATA); resolve(window.EXAM_SCHEDULE_DATA) }
          document.head.appendChild(script)
        })
    })
  }, [data])

  const doQuery = useCallback(async (id) => {
    if (!id || !id.trim()) return
    setLoading(true)
    try {
      const d = await loadData()
      if (!d) { setMsg({ text: '加载考试数据失败，请稍后再试。', type: 'error' }); setLoading(false); return }
      id = id.trim().toUpperCase()

    let targetId = id, examsArr = d[id]
    if (!examsArr) {
      const matches = Object.keys(d).filter(k => k.indexOf(id) !== -1)
      if (matches.length === 1) { targetId = matches[0]; examsArr = d[targetId] }
      else if (matches.length > 1) { setMsg({ text: '多个匹配：' + matches.slice(0, 8).join('、') + '，请输入完整 ID。', type: 'warn' }); return }
      else { setMsg({ text: '未找到班级「' + id + '」的考试安排。', type: 'warn' }); return }
    }

    setQueryId(targetId)
    try { localStorage.setItem(LS_KEY, targetId) } catch (e) {}
    cleanOldDeleted(targetId)

    const now = new Date()
    let delCnt = 0
    const visible = examsArr.filter(e => {
      if (new Date(e.iso) < now) return false
      if (isDeleted(targetId, getCourseKey(e))) { delCnt++; return false }
      return true
    })

    setExams(visible)
    setDeletedCount(delCnt)
    setShowResult(true)
    setMsg(null)
    setDeletedMap(getDeletedExams())

    if (refreshRef.current) clearInterval(refreshRef.current)
    refreshRef.current = setInterval(() => { doQuery(targetId) }, 3600000)
    } catch (e) {
      setMsg({ text: '查询出错：' + (e.message || '未知错误'), type: 'error' })
    } finally {
      setLoading(false)
    }
  }, [loadData])

  useEffect(() => {
    const saved = localStorage.getItem(LS_KEY)
    if (saved) { setClassId(saved); doQuery(saved) }
    else loadData()
    return () => clearInterval(refreshRef.current)
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const removeExam = (exam, btn) => {
    const card = btn.closest('.exam-card')
    if (!card) return
    const key = getCourseKey(exam)
    markDeleted(queryId, key)
    card.style.transition = 'opacity .25s, transform .25s'
    card.style.opacity = '0'; card.style.transform = 'scale(0.9)'
    setTimeout(() => {
      card.remove()
      const rem = document.querySelectorAll('.exam-card').length
      const countEl = document.querySelector('.exam-count')
      if (countEl) countEl.textContent = rem + ' 门'
      if (rem === 0) { setShowResult(false); setMsg({ text: '所有考试已结束或已清除，切换班级可重新查询。', type: 'warn' }) }
    }, 280)
  }

  const clearQuery = () => {
    try { localStorage.removeItem(LS_KEY) } catch (e) {}
    clearInterval(refreshRef.current)
    setQueryId(''); setExams([]); setShowResult(false); setMsg(null); setClassId('')
    setTimeout(() => document.getElementById('examClassInput')?.focus(), 50)
  }

  const resetDeleted = () => {
    const d = getDeletedExams()
    delete d[queryId]
    try { localStorage.setItem(LS_DELETED, JSON.stringify(d)) } catch (e) {}
    setDeletedMap(d)
    doQuery(queryId)
  }

  return (
    <div className="exam-section">
      <div id="examInput" className="exam-input-wrap" style={{ display: showResult ? 'none' : undefined }}>
        <div className="exam-input-title">📅 查询考试安排</div>
        <div className="exam-input-row">
          <input id="examClassInput" type="text" placeholder="输入班级 ID（如 B220207）"
            value={classId} onChange={e => setClassId(e.target.value)}
            onKeyDown={e => { if (e.key === 'Enter') doQuery(classId) }}
            autoComplete="off" spellCheck="false" />
          <button onClick={() => doQuery(classId)} disabled={loading}>
            {loading ? '加载中…' : '查询'}
          </button>
        </div>
        <div className="exam-input-hint">输入班级 ID 即可查看该班所有考试时间、教室和教师信息</div>
        {msg && <div className={`exam-msg exam-msg-${msg.type}`} style={{ marginTop: 12 }}>{msg.text}</div>}
      </div>

      {showResult && (
        <div className="exam-result">
          <div className="exam-header">
            <div className="exam-title">
              <span className="exam-class-badge">{queryId}</span>
              考试安排
              <span className="exam-count">{exams.length} 门</span>
            </div>
            <div className="exam-header-btns">
              {deletedCount > 0 && <button className="exam-reset" onClick={resetDeleted}>恢复 {deletedCount} 门</button>}
              <button className="exam-switch" onClick={clearQuery}>切换班级</button>
            </div>
          </div>
          {exams.length === 0 ? (
            <div className="exam-msg exam-msg-warn">所有考试已结束或已清除，切换班级可重新查询。</div>
          ) : (
            <>
              <div className="exam-scroll-window">
                <div className="exam-list">
                  {exams.map((ev, j) => {
                    const cd = getCountdown(ev.iso)
                    return (
                      <div className="exam-card" key={j}>
                        <button className="exam-del" onClick={(e) => removeExam(ev, e.target)} title="移除">&times;</button>
                        <div className="exam-card-top">
                          <div className="exam-course">{ev.course}</div>
                          <span className={`exam-type-tag exam-type-${ev.type}`}>{ev.type === 'school' ? '校考' : '院考'}</span>
                        </div>
                        <div className="exam-card-grid">
                          <div className="exam-info"><span className="exam-label">日期</span><span className="exam-value">{formatDate(ev.date)}</span></div>
                          <div className="exam-info"><span className="exam-label">时间</span><span className="exam-value">{ev.start} - {ev.end}</span></div>
                          <div className="exam-info"><span className="exam-label">教室</span><span className="exam-value">{ev.room}</span></div>
                          <div className="exam-info"><span className="exam-label">教师</span><span className="exam-value">{ev.teacher}</span></div>
                        </div>
                        {cd && <div className="exam-countdown">距考试还有 {cd}</div>}
                      </div>
                    )
                  })}
                </div>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  )
}
