// src/features/search/GlobalSearch.vue
<script setup lang="ts">
/**
 * GlobalSearch — 替代 React 的 features/search/GlobalSearch.jsx
 * 全局文件搜索框，使用 Fuse.js 模糊匹配。
 */
import { ref, onMounted, onUnmounted } from 'vue'
import { FILES } from '../../data/files'

interface FileEntry {
  n: string // name
  sn: string // subject name
  tn: string // type name
  sz: string // size
  s: string // subject
  t: string // type
  p: string // path
  c: string // color
}

const query = ref('')
const results = ref<FileEntry[]>([])
const focused = ref(false)
const selectedIdx = ref(-1)
const inputRef = ref<HTMLInputElement | null>(null)

let fuse: any = null

function fileUrl(f: FileEntry) {
  return f.p.startsWith('http') ? f.p : '/' + f.p
}

function doSearch(q: string) {
  query.value = q
  selectedIdx.value = -1
  if (!q.trim() || !fuse) {
    results.value = []
    return
  }

  results.value = fuse
    .search(q)
    .slice(0, 10)
    .map((m: any) => m.item)
}

function openFile(f: FileEntry) {
  window.open(fileUrl(f), '_blank')
  focused.value = false
}

function onKeydown(e: KeyboardEvent) {
  if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
    e.preventDefault()
    inputRef.value?.focus()
  }
  if (e.key === '/' && !e.ctrlKey && !e.metaKey && (e.target as HTMLElement).tagName !== 'INPUT') {
    e.preventDefault()
    inputRef.value?.focus()
  }
  if (e.key === 'Escape') {
    focused.value = false
    inputRef.value?.blur()
  }
}

function onInputKeydown(e: KeyboardEvent) {
  if (e.key === 'ArrowDown') {
    e.preventDefault()
    selectedIdx.value = Math.min(selectedIdx.value + 1, results.value.length - 1)
  }
  if (e.key === 'ArrowUp') {
    e.preventDefault()
    selectedIdx.value = Math.max(selectedIdx.value - 1, 0)
  }
  if (e.key === 'Enter' && selectedIdx.value >= 0 && results.value[selectedIdx.value]) {
    openFile(results.value[selectedIdx.value])
  }
}

onMounted(() => {
  const script = document.createElement('script')
  script.src = 'https://cdn.jsdelivr.net/npm/fuse.js@7.0.0/dist/fuse.min.js'
  script.onload = () => {
    if ((window as unknown as Record<string, unknown>)['Fuse']) {
      fuse = new (window as any).Fuse(FILES, {
        keys: ['n', 'sn'],
        threshold: 0.4,
        includeScore: true,
      })
    }
  }
  document.head.appendChild(script)
  window.addEventListener('keydown', onKeydown)
})

onUnmounted(() => window.removeEventListener('keydown', onKeydown))

function onBlur() {
  setTimeout(() => {
    focused.value = false
  }, 200)
}
</script>

<template>
  <div class="search-section gs-wrap">
    <div class="gs-input-wrap">
      <span class="gs-icon">🔍</span>
      <input
        ref="inputRef"
        :value="query"
        placeholder="搜索知识点、资料名称… (Ctrl+K)"
        class="gs-input"
        @input="doSearch(($event.target as HTMLInputElement).value)"
        @focus="focused = true"
        @blur="onBlur"
        @keydown="onInputKeydown"
      />
    </div>
    <div v-if="focused && results.length > 0" class="gs-dropdown">
      <div
        v-for="(f, i) in results"
        :key="i"
        class="gs-item"
        :class="{ 'gs-item--active': i === selectedIdx }"
        @click="openFile(f)"
        @mouseenter="selectedIdx = i"
      >
        <div class="gs-item-name">{{ f.n }}</div>
        <div class="gs-item-meta">
          <span class="gs-tag" :style="{ background: f.c + '20', color: f.c }">{{ f.sn }}</span>
          <span>{{ f.tn }}</span>
          <span class="gs-size">{{ f.sz }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.gs-wrap {
  max-width: 560px;
  margin: 0 auto 28px;
  position: relative;
  z-index: 100;
}
.gs-input-wrap {
  position: relative;
}
.gs-icon {
  position: absolute;
  left: 14px;
  top: 50%;
  transform: translateY(-50%);
  color: var(--text3);
  font-size: 1rem;
  pointer-events: none;
}
.gs-input {
  width: 100%;
  padding: 12px 16px 12px 40px;
  border-radius: 12px;
  border: 1px solid var(--border);
  background: var(--card);
  color: var(--text);
  font-size: 0.92rem;
  outline: none;
  box-sizing: border-box;
}
.gs-dropdown {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  margin-top: 6px;
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 12px;
  max-height: 420px;
  overflow-y: auto;
  z-index: 200;
  box-shadow: 0 8px 30px rgba(0, 0, 0, 0.2);
}
.gs-item {
  padding: 10px 16px;
  cursor: pointer;
  font-size: 0.85rem;
  border-bottom: 1px solid var(--border);
}
.gs-item--active {
  background: var(--accent-bg, rgba(108, 138, 255, 0.1));
}
.gs-item-name {
  font-weight: 600;
  color: var(--text);
}
.gs-item-meta {
  font-size: 0.75rem;
  color: var(--text3);
  margin-top: 2px;
}
.gs-tag {
  padding: 1px 6px;
  border-radius: 4px;
  margin-right: 6px;
}
.gs-size {
  margin-left: 6px;
}
</style>

// src/features/search/GlobalSearch.jsx
import { useState, useRef, useEffect, useCallback } from 'react'
import { FILES } from '../../data/files'

export default function GlobalSearch() {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState([])
  const [focus, setFocus] = useState(false)
  const [selectedIdx, setSelectedIdx] = useState(-1)
  const inputRef = useRef(null)
  const fuseRef = useRef(null)

  // Load Fuse.js on mount
  useEffect(() => {
    const script = document.createElement('script')
    script.src = 'https://cdn.jsdelivr.net/npm/fuse.js@7.0.0/dist/fuse.min.js'
    script.onload = () => {
      if (window.Fuse) {
        fuseRef.current = new window.Fuse(FILES, {
          keys: ['n', 'sn'],
          threshold: 0.4,
          includeScore: true,
        })
      }
    }
    document.head.appendChild(script)
    // Keyboard shortcut: Ctrl+K or /
    const handler = (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
        e.preventDefault(); inputRef.current?.focus()
      }
      if (e.key === '/' && !e.ctrlKey && !e.metaKey && e.target.tagName !== 'INPUT') {
        e.preventDefault(); inputRef.current?.focus()
      }
      if (e.key === 'Escape') { setFocus(false); inputRef.current?.blur() }
    }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [])

  const doSearch = useCallback((q) => {
    setQuery(q)
    setSelectedIdx(-1)
    if (!q.trim() || !fuseRef.current) { setResults([]); return }
    const r = fuseRef.current.search(q).slice(0, 10)
    setResults(r.map(m => m.item))
  }, [])

  const fileUrl = (f) => f.p.startsWith('http') ? f.p : '/' + f.p

  const openFile = (f) => {
    window.open(fileUrl(f), '_blank')
    setFocus(false)
  }

  return (
    <div className="search-section" style={{ maxWidth: 560, margin: '0 auto 28px', position: 'relative', zIndex: 100 }}>
      <div style={{ position: 'relative' }}>
        <span style={{ position: 'absolute', left: 14, top: '50%', transform: 'translateY(-50%)', color: 'var(--text3)', fontSize: '1rem', pointerEvents: 'none' }}>🔍</span>
        <input
          ref={inputRef}
          value={query} onChange={e => doSearch(e.target.value)}
          onFocus={() => setFocus(true)}
          onBlur={() => setTimeout(() => setFocus(false), 200)}
          placeholder="搜索知识点、资料名称… (Ctrl+K)"
          onKeyDown={(e) => {
            if (e.key === 'ArrowDown') { e.preventDefault(); setSelectedIdx(i => Math.min(i + 1, results.length - 1)) }
            if (e.key === 'ArrowUp') { e.preventDefault(); setSelectedIdx(i => Math.max(i - 1, 0)) }
            if (e.key === 'Enter' && selectedIdx >= 0 && results[selectedIdx]) openFile(results[selectedIdx])
          }}
          style={{
            width: '100%', padding: '12px 16px 12px 40px', borderRadius: 12,
            border: '1px solid var(--border)', background: 'var(--card)', color: 'var(--text)',
            fontSize: '.92rem', outline: 'none', boxSizing: 'border-box',
          }}
        />
      </div>
      {focus && results.length > 0 && (
        <div style={{
          position: 'absolute', top: '100%', left: 0, right: 0, marginTop: 6,
          background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 12,
          maxHeight: 420, overflowY: 'auto', zIndex: 200,
          boxShadow: '0 8px 30px rgba(0,0,0,.2)',
        }}>
          {results.map((f, i) => (
            <div key={i} onClick={() => openFile(f)} onMouseEnter={() => setSelectedIdx(i)} style={{
              padding: '10px 16px', cursor: 'pointer', fontSize: '.85rem',
              background: i === selectedIdx ? 'var(--accent-bg)' : 'transparent',
              borderBottom: '1px solid var(--border)',
            }}>
              <div style={{ fontWeight: 600, color: 'var(--text)' }}>{f.n}</div>
              <div style={{ fontSize: '.75rem', color: 'var(--text3)', marginTop: 2 }}>
                <span style={{ background: f.c + '20', color: f.c, padding: '1px 6px', borderRadius: 4, marginRight: 6 }}>{f.sn}</span>
                <span>{f.tn}</span>
                <span style={{ marginLeft: 6 }}>{f.sz}</span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
