// src/features/print-mode/PrintModeFAB.vue
<script setup lang="ts">
/**
 * PrintModeFAB — 替代 React 的 features/print-mode/PrintModeFAB.jsx
 * 浮动按钮，一键切换打印优化模式。
 */
import { ref } from 'vue'

const PRINT_CSS = `
body.f2-print-mode{background:#fff!important;color:#1a1a1a!important}
body.f2-print-mode .main,main{margin:0!important;padding:16px!important;max-width:100%!important}
body.f2-print-mode .sidebar,.sidebar{display:none!important}
body.f2-print-mode nav,header,footer,.fab-group{display:none!important}
body.f2-print-mode .section{border:none!important;padding:0!important}
body.f2-print-mode table{font-size:.85rem}
body.f2-print-mode pre{border:1px solid #ccc;overflow:visible;white-space:pre-wrap}
@media print{body.f2-print-mode .no-print{display:none!important}}
`

const active = ref(false)
let styleEl: HTMLStyleElement | null = null

function toggle() {
  active.value = !active.value
  if (active.value) {
    styleEl = document.createElement('style')
    styleEl.textContent = PRINT_CSS
    document.head.appendChild(styleEl)
    document.body.classList.add('f2-print-mode')
  } else {
    styleEl?.remove()
    document.body.classList.remove('f2-print-mode')
  }
}
</script>

<template>
  <button class="pm-fab" :title="active ? '退出打印模式' : '打印优化模式'" @click="toggle">
    🖨
  </button>
</template>

<style scoped>
.pm-fab {
  position: fixed;
  bottom: 85px;
  right: 30px;
  z-index: 98;
  width: 44px;
  height: 44px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--card, #1e2235);
  color: var(--text);
  border: 1px solid var(--border);
  cursor: pointer;
  font-size: 1.2em;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
  transition: transform 0.2s;
}
.pm-fab:hover {
  transform: scale(1.1);
}
</style>

// src/features/print-mode/PrintModeFAB.jsx
import { useEffect } from 'react'

const PRINT_CSS = `
body.f2-print-mode{background:#fff!important;color:#1a1a1a!important}
body.f2-print-mode .main,main{margin:0!important;padding:16px!important;max-width:100%!important}
body.f2-print-mode nav,body.f2-print-mode .sidebar,body.f2-print-mode .sidebar-overlay,
body.f2-print-mode .nav-toggle,body.f2-print-mode .back-top,body.f2-print-mode .theme-toggle,
body.f2-print-mode [style*="position:fixed"],body.f2-print-mode .progress-bar,
body.f2-print-mode .sg-overlay,body.f2-print-mode .ux-marker,body.f2-print-mode .ux-back-to-marker{display:none!important}
body.f2-print-mode .card,body.f2-print-mode .section,body.f2-print-mode .quiz-container{background:#fff!important;border:1px solid #ddd!important;box-shadow:none!important;page-break-inside:avoid}
body.f2-print-mode .kb{background:#f7f7f7!important;border-left:4px solid #2563eb!important}
body.f2-print-mode .kb th{background:#2563eb!important;color:#fff!important}
body.f2-print-mode .quiz-correct{background:#dcfce7!important;color:#166534!important;border:1px solid #86efac!important}
body.f2-print-mode .quiz-wrong{background:#fef2f2!important;color:#991b1b!important;border:1px solid #fca5a5!important}
body.f2-print-mode img,body.f2-print-mode svg{max-width:100%!important}
body.f2-print-mode .collapsible-content{max-height:none!important;opacity:1!important;display:block!important}
body.f2-print-mode .section.collapsed .section-body{max-height:none!important;opacity:1!important;padding-bottom:20px!important}
body.f2-print-mode .section-divider{display:none!important}
body.f2-print-mode table{width:100%!important}
`

/**
 * Injects print-optimized CSS and provides a FAB button.
 * Replaces print-mode.js.
 */
export default function PrintModeFAB() {
  useEffect(() => {
    const style = document.createElement('style')
    style.textContent = PRINT_CSS
    document.head.appendChild(style)
    return () => style.remove()
  }, [])

  const printPage = () => {
    document.body.classList.add('f2-print-mode')
    setTimeout(() => {
      window.print()
      setTimeout(() => document.body.classList.remove('f2-print-mode'), 500)
    }, 100)
  }

  return (
    <button onClick={printPage} title="打印优化模式" style={{
      position: 'fixed', bottom: 305, right: 30, zIndex: 98,
      width: 44, height: 44, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center',
      background: 'var(--card2,#22263a)', color: 'var(--text)', border: '1px solid var(--border)',
      cursor: 'pointer', fontSize: '1.2em', boxShadow: '0 4px 15px rgba(0,0,0,.3)', transition: 'transform .2s',
    }}>🖨</button>
  )
}
