// src/features/wrong-book/WrongBookFAB.jsx
import { useState } from 'react'
import useWrongBook from './useWrongBook'

export default function WrongBookFAB() {
  const [open, setOpen] = useState(false)
  const { wrongs, clearAll, exportAsText, grouped } = useWrongBook()
  const [filter, setFilter] = useState('all')

  const groups = grouped()
  const pages = Object.keys(groups)
  const filtered = filter === 'all' ? wrongs : (groups[filter] || [])

  return (
    <>
      {/* FAB Button */}
      <button
        onClick={() => setOpen(!open)}
        title="错题本"
        style={{
          position: 'fixed', bottom: 140, right: 30, zIndex: 98,
          width: 44, height: 44, borderRadius: '50%',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          background: 'var(--red,#ef4444)', color: '#fff', border: 'none',
          cursor: 'pointer', fontSize: '1.2em', boxShadow: '0 4px 15px rgba(0,0,0,.3)',
          transition: 'transform .2s',
        }}
        onMouseEnter={e => e.currentTarget.style.transform = 'scale(1.1)'}
        onMouseLeave={e => e.currentTarget.style.transform = 'scale(1)'}
      >
        📝
        {wrongs.length > 0 && (
          <span style={{
            position: 'absolute', top: -4, right: -4, minWidth: 20, height: 20,
            borderRadius: 10, background: '#fff', color: 'var(--red,#ef4444)',
            fontSize: '.7rem', fontWeight: 700, display: 'flex', alignItems: 'center',
            justifyContent: 'center', padding: '0 4px',
          }}>{wrongs.length}</span>
        )}
      </button>

      {/* Modal */}
      {open && (
        <div onClick={(e) => { if (e.target === e.currentTarget) setOpen(false) }}
          style={{
            display: 'flex', position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
            zIndex: 10000, background: 'rgba(0,0,0,.5)', alignItems: 'center', justifyContent: 'center',
          }}>
          <div style={{
            background: 'var(--card,#1a1d27)', borderRadius: 16, padding: 28,
            maxWidth: 720, width: '92vw', maxHeight: '80vh', overflowY: 'auto',
            border: '1px solid var(--border,#2d3436)', position: 'relative',
          }}>
            <button onClick={() => setOpen(false)} style={{
              position: 'absolute', top: 12, right: 16, background: 'none', border: 'none',
              cursor: 'pointer', fontSize: '1.3rem', color: 'var(--text3,#8892b0)', lineHeight: 1,
            }}>&times;</button>
            <h3 style={{ margin: '0 0 16px', fontSize: '1.15rem', color: 'var(--accent2,#a29bfe)' }}>📝 错题本</h3>

            {/* Tab filter */}
            <div style={{ display: 'flex', gap: 6, marginBottom: 16, flexWrap: 'wrap' }}>
              <button onClick={() => setFilter('all')} style={{
                padding: '6px 16px', borderRadius: 8, border: '1px solid var(--border)',
                background: filter === 'all' ? 'var(--accent,#6c5ce7)' : 'transparent',
                color: filter === 'all' ? '#fff' : 'var(--text-dim,#8892b0)',
                cursor: 'pointer', fontSize: '.85rem', fontWeight: 600,
              }}>全部 ({wrongs.length})</button>
              {pages.map(p => (
                <button key={p} onClick={() => setFilter(p)} style={{
                  padding: '6px 16px', borderRadius: 8, border: '1px solid var(--border)',
                  background: filter === p ? 'var(--accent,#6c5ce7)' : 'transparent',
                  color: filter === p ? '#fff' : 'var(--text-dim,#8892b0)',
                  cursor: 'pointer', fontSize: '.85rem', fontWeight: 600,
                }}>{p} ({groups[p].length})</button>
              ))}
            </div>

            {/* Wrong items */}
            {filtered.length === 0 ? (
              <p style={{ color: 'var(--text-dim,#8892b0)' }}>暂无错题，继续加油！</p>
            ) : (
              filtered.slice().reverse().map((w, i) => (
                <div key={i} style={{
                  background: 'var(--card2,#232736)', borderRadius: 10,
                  padding: '14px 16px', margin: '8px 0', border: '1px solid var(--border,#2d3436)',
                }}>
                  <div style={{ fontWeight: 600, marginBottom: 6, fontSize: '.92rem' }}>{w.question}</div>
                  <div style={{ fontSize: '.85rem', color: 'var(--text-dim,#8892b0)' }}>
                    <span style={{ color: 'var(--red,#ff6b6b)' }}>✗ 你的答案: {w.userAnswer}</span><br />
                    <span style={{ color: 'var(--green,#00cec9)' }}>✓ 正确答案: {w.correctAnswer}</span>
                  </div>
                  <div style={{ fontSize: '.72rem', color: 'var(--text-dim,#8892b0)', marginTop: 4 }}>
                    {new Date(w.time).toLocaleString()}
                  </div>
                </div>
              ))
            )}

            {/* Actions */}
            {wrongs.length > 0 && (
              <div style={{ marginTop: 16, display: 'flex', gap: 8 }}>
                <button onClick={() => { if (confirm('确定清空所有错题？')) clearAll() }} style={{
                  background: 'var(--red,#ff6b6b)', color: '#fff', border: 'none',
                  padding: '8px 18px', borderRadius: 8, cursor: 'pointer', fontSize: '.82rem',
                }}>清空错题</button>
                <button onClick={exportAsText} style={{
                  background: 'var(--card2,#22263a)', color: 'var(--text)', border: '1px solid var(--border)',
                  padding: '8px 18px', borderRadius: 8, cursor: 'pointer', fontSize: '.82rem',
                }}>导出为文本</button>
              </div>
            )}
          </div>
        </div>
      )}
    </>
  )
}

// src/features/wrong-book/WrongBookFAB.vue
<script setup lang="ts">
/**
 * WrongBookFAB — 替代 React 的 features/wrong-book/WrongBookFAB.jsx
 * 错题本浮动按钮及弹窗，支持按页面分组、清空和导出。
 */
import { ref, computed } from 'vue'
import { useWrongBook } from '../../composables/useWrongBook'

const { wrongs, clearAll, exportAsText, grouped } = useWrongBook()
const open = ref(false)
const filter = ref('all')

const groups = computed(() => grouped())
const pages = computed(() => Object.keys(groups.value))
const filtered = computed(() =>
  filter.value === 'all' ? wrongs.value : groups.value[filter.value] || [],
)

function confirmClearAll() {
  if (window.confirm('确定清空所有错题？')) clearAll()
}
</script>

<template>
  <!-- FAB 按钮 -->
  <button class="wb-fab" title="错题本" @click="open = !open">
    📝
    <span v-if="wrongs.length > 0" class="wb-badge">{{ wrongs.length }}</span>
  </button>

  <!-- 弹窗 -->
  <Teleport to="body">
    <div v-if="open" class="wb-overlay" @click.self="open = false">
      <div class="wb-panel">
        <button class="wb-close" @click="open = false">&times;</button>
        <h3 class="wb-title">📝 错题本</h3>

        <!-- 分组 tab -->
        <div class="wb-tabs">
          <button :class="['wb-tab', { active: filter === 'all' }]" @click="filter = 'all'">
            全部 ({{ wrongs.length }})
          </button>
          <button
            v-for="p in pages"
            :key="p"
            :class="['wb-tab', { active: filter === p }]"
            @click="filter = p"
          >
            {{ p }} ({{ groups[p].length }})
          </button>
        </div>

        <!-- 错题列表 -->
        <p v-if="filtered.length === 0" class="wb-empty">暂无错题，继续加油！</p>
        <div v-else>
          <div v-for="(w, i) in [...filtered].reverse()" :key="i" class="wb-item">
            <div class="wb-question">{{ w.question }}</div>
            <div class="wb-answers">
              <span class="wb-wrong">✗ 你的答案: {{ w.userAnswer }}</span
              ><br />
              <span class="wb-correct">✓ 正确答案: {{ w.correctAnswer }}</span>
            </div>
            <div class="wb-time">{{ new Date(w.time).toLocaleString() }}</div>
          </div>
        </div>

        <!-- 操作 -->
        <div v-if="wrongs.length > 0" class="wb-actions">
          <button class="wb-btn wb-btn-clear" @click="confirmClearAll">清空错题</button>
          <button class="wb-btn wb-btn-export" @click="exportAsText">导出为文本</button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.wb-fab {
  position: fixed;
  bottom: 140px;
  right: 30px;
  z-index: 98;
  width: 44px;
  height: 44px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--red, #ef4444);
  color: #fff;
  border: none;
  cursor: pointer;
  font-size: 1.2em;
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.3);
  transition: transform 0.2s;
}
.wb-fab:hover {
  transform: scale(1.1);
}
.wb-badge {
  position: absolute;
  top: -4px;
  right: -4px;
  min-width: 20px;
  height: 20px;
  border-radius: 10px;
  background: #fff;
  color: var(--red, #ef4444);
  font-size: 0.7rem;
  font-weight: 700;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0 4px;
}
.wb-overlay {
  position: fixed;
  inset: 0;
  z-index: 10000;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
}
.wb-panel {
  background: var(--card, #1a1d27);
  border-radius: 16px;
  padding: 28px;
  max-width: 720px;
  width: 92vw;
  max-height: 80vh;
  overflow-y: auto;
  border: 1px solid var(--border);
  position: relative;
}
.wb-close {
  position: absolute;
  top: 12px;
  right: 16px;
  background: none;
  border: none;
  font-size: 1.3rem;
  color: var(--text3);
  cursor: pointer;
  line-height: 1;
}
.wb-title {
  margin: 0 0 16px;
  font-size: 1.15rem;
  color: var(--accent2, #a29bfe);
}
.wb-tabs {
  display: flex;
  gap: 6px;
  margin-bottom: 16px;
  flex-wrap: wrap;
}
.wb-tab {
  padding: 6px 16px;
  border-radius: 8px;
  border: 1px solid var(--border);
  background: transparent;
  color: var(--text2);
  cursor: pointer;
  font-size: 0.85rem;
  font-weight: 600;
}
.wb-tab.active {
  background: var(--accent, #6c5ce7);
  color: #fff;
  border-color: var(--accent);
}
.wb-empty {
  color: var(--text2);
}
.wb-item {
  background: var(--card2, #232736);
  border-radius: 10px;
  padding: 14px 16px;
  margin: 8px 0;
  border: 1px solid var(--border);
}
.wb-question {
  font-weight: 600;
  margin-bottom: 6px;
  font-size: 0.92rem;
}
.wb-answers {
  font-size: 0.85rem;
  color: var(--text2);
}
.wb-wrong {
  color: var(--red, #ff6b6b);
}
.wb-correct {
  color: var(--green, #00cec9);
}
.wb-time {
  font-size: 0.72rem;
  color: var(--text3);
  margin-top: 4px;
}
.wb-actions {
  margin-top: 16px;
  display: flex;
  gap: 8px;
}
.wb-btn {
  border: none;
  padding: 8px 18px;
  border-radius: 8px;
  cursor: pointer;
  font-size: 0.82rem;
}
.wb-btn-clear {
  background: var(--red, #ff6b6b);
  color: #fff;
}
.wb-btn-export {
  background: var(--card2, #22263a);
  color: var(--text);
  border: 1px solid var(--border);
}
</style>
